### ISSUE TITLE
Intent ?

### ISSUE THREAD

**Issue by gedw99** [hack-pad/go-webworkers#2]
Is the goal to get the fs system working as Service worker ? 

or for web workers to use indexdb as a durable bus ?

Am curious :)

**Comment by JohnStarich** [comment]
Hey @gedw99! This library is intended to make Web Worker interop easier. Specifically, I'd like to use it to build more useful tools on top. I had difficulty ensuring message passing was working as intended, so this library will likely grow significantly into the message passing arena.

For Hackpad, I'd like to initialize workers with the Go script, execute a Wasm binary, and set up the same file system used Hackpad's main thread. It's complex enough I wanted to yank out the message passing into a separate lib. And here we are 😄

**Comment by gedw99** [comment]
Very cool :) 

a mini demo coming one day ?

**Comment by JohnStarich** [comment]
That's the plan! Finding time is difficult, as always 😄

**Comment by gedw99** [comment]
Hey @JohnStarich 

I am porting this bud to also work in web workers …

https://github.com/gedw99/skel

The readme explains it harshly but it should be obvious I think once you try it on desktop and then was wasm

i see synergy with your hackpad.

there is a full golang debugger using delve also written with gioui 

i am pondering extending Nats.go to work in process also so it can also work inside PWA and native apps . I might be bitting off mitre than is worthwhile though.

https://github.com/nats-io/nats-server/blob/main/server/client.go#L39


happy to discuss ideas etc . Just should.


FYI @oderwat

**Comment by oderwat** [comment]
@gedw99 

> https://github.com/nats-io/nats-server/blob/main/server/client.go#L39

Points to the functional type of the connection.

The following point is seemingly more relevant:

> https://github.com/nats-io/nats-server/blob/b61e411b44af43a125f89e549d0ac7337c88db89/server/client.go#L544

Even when NATS at its core just has a simple string-based protocol, there is a lot of stuff going on for connection handling (as it has to switch servers / clusters / exchanging data between nodes / raft and so on). I guess that the Websocket implementation could be a "basis" for another types of connections.

If I would "at all" consider using NATS with another transport, I would probably think about emulating TCP on top of some other (event) system. TCP is also just packages in the end.

> https://github.com/jordwest/mock-conn
> https://github.com/WebAssembly/wasi-sockets

Adding all of 'nats-server', plus all of  'nats.go' (which also implements a lot of the functionality on top) seems quite a bit of overhead for something that is already there between web workers: "events". I really don't see the utility. NATS works with central servers (spreading the nodes and clusters around the world, does not change that),

I may muss the point. I already have a hard time understanding that is in your mind @gedw99. Why just using TCP? Isn't a WebWorker not already using TCP in the first place?

**Comment by gedw99** [comment]
hey - thansk fro writing back.

i agree this is complex and 90% not worthwhile. I just wanted to get a second option...

emulating TCP sounds like a nice option.

the bit about not understanding the why is that web workers communicate with Service workers over message passing inside the browser, not over tcp.
https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

golang sample: https://blog.boot.dev/golang/running-go-in-the-browser-wasm-web-workers/

its a bit old though :)

Please feel free to ask if anything not clear...

**Comment by oderwat** [comment]
@gedw99 If you are inside the same browser, the message flow seems trivial to me. I thought you needed a connection between different browsers. I actually never considered having the same PWA opened in multiple Tabs in the browser to exchange data between each other. Likewise, I just use IndexedDB when I need to share data between them or go "outside" over web socket to the nats-server and back. This is because we usually need to support the same PWA also working on another browser or "desktop" and some data must be everywhere anyway. Like on different tablets for synchronized time logging at multiple check in / out points for workers in huge storage facilities. For "multiple tab" scenarios, I would just use one browser tab. Why starting many ones, they are resource hogs.

**Comment by gedw99** [comment]
yeah sorry been a long day :)

My use case is exactly the same as yours but with a few twists i think..

Yeah i remember we had a chat ages ago about IndexedDB. Not sure i need it. Not doing offline first as then we get into awful data sync and out of order merges.. Maybe another day... One step at a time.

So as far as i can tell the data flows / connections in totality are:

1. Within a PWA ( service workers <--> web worker ). 

- That will sync any tabs on the same computer.

- Good old post message. Hence why @JohnStarich 's go-webworker is the way to go..

2. Between a PAW and a server ( Service worker <--> golang NATS server ). That will sync any tab between computers.

- WASM nats.go client and NATS Server
- Need Presence my precious ( sorry lord of rings pun ).  Got to look at how to do that in nats ...

3. On Desktop Between a GUI and spawned gui windows.  ( Desktop main gui <--> desktop spawned  gui windows ). 

- That will sync a single window  to any spawned windows on the same computer

- Golang Bus between windows.  I want to try to make johns go-webworker be agnostic enough to work here.  Just a matter of adapting the current Desktop bus code with John's code. Use go build tags and file names to keep sane.

4. On Desktop between Service ( launchd, etc ) and many GUI ( Desktop Service <--> desktop gui(s) ).  

- That will sync all windows on same computer  with NATS Leaf on that same computer. 
- Each Window will then sync with its swamned windows using 3 ( above )


5. Lastly On anything ( Golang NAT Server  (s) to Browser or Desk ). 

- This is NATS Server in HA mode, etc  talking to everything...



I really need a diagram :)

**Comment by gedw99** [comment]
Am going to close this as we got off topic
